server:
  address: 127.0.0.1
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/anyue_db
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
